---
name: '📦 Create New Release'

on:
  push:
    branches:
      - master

permissions:
  contents: write
  actions: read
  pull-requests: write
  issues: write
  deployments: write

concurrency:
  group: release-master-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: ✅ Check for Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      HUSKY: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧪 Check out repository code
        uses: ./.github/workflows/health-check
        with:
          run-tests: false
          run-tests-command: 'npx nx affected --target=test --parallel'
          run-lint: false
          run-lint-command: 'npx nx affected --target=lint --parallel'
          run-build: true
          run-build-command: 'npx nx affected --target=build --parallel'

  release:
    name: 📦 Release Version
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - checks

    env:
      HUSKY: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}

      - name: 🖥️ Setup Env
        uses: ./.github/workflows/install

      - name: Release
        timeout-minutes: 2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          npx nx release
